version: "3"

services:
  db:
    image: postgres
    ports:
      - 5426:5432
    environment:
        POSTGRES_PASSWORD: postgres


  pytest:
    command: ["poetry", "run", "pytest"]
    ports:
      - 8081:8081
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - .:/app
    depends_on:
      - db