version: "3"

services:
  test_db:
    image: postgres
    ports:
      - 5426:5432
    environment:
        POSTGRES_PASSWORD: postgres


  pytest:
    command: bash -c "sh run_migrations.sh && poetry run pytest"
    ports:
      - 8081:8081
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: test_db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - .:/app
    depends_on:
      - test_db